In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
df=pd.read_csv("spam.csv")
df.sample(3)

     Category                            Message
1066      ham          No my mum went 2 dentist.
3284      ham  Hey tmr maybe can meet you at yck
756       ham            So why didnt you holla?

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [3]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(415)

In [6]:
df = df.drop_duplicates()

In [7]:
df.shape

(5157, 2)

In [8]:
df["Category"].value_counts()

Category
ham     4516
spam     641
Name: count, dtype: int64

In [9]:
df["Category"] = df["Category"].map({
    "ham": 0,
    "spam": 1
})
df.head(3)

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...

In [10]:
X = df["Message"]
y = df["Category"]

In [11]:
X.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: Message, dtype: object

In [12]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Category, dtype: int64

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(X)

In [14]:
X.shape

(5157, 8709)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [16]:
X_train.shape

(4125, 8709)

In [17]:
X_test.shape

(1032, 8709)

In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [19]:
y_pred = model.predict(X_test)
y_pred[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [20]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9554263565891473

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[896   0]
 [ 46  90]]

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       896
           1       1.00      0.66      0.80       136

    accuracy                           0.96      1032
   macro avg       0.98      0.83      0.89      1032
weighted avg       0.96      0.96      0.95      1032

In [23]:
import pickle

pickle.dump(model, open("Naive_model.pkl", "wb"))
pickle.dump(tfidf, open("Naive_vectorizer.pkl", "wb"))

In [24]:
df["Category"].value_counts()

Category
0    4516
1     641
Name: count, dtype: int64

In [25]:
pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Requirement already satisfied: imbalanced-learn in c:\users\venth\anaconda3\lib\site-packages (from imblearn) (0.14.0)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\venth\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (2.3.5)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\venth\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\venth\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.7.2)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\venth\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\venth\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: imblearn
Successfully installed imblearn-0.0
Note: you may need to restart the kernel to use updated packages.

In [26]:

from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)
print("Original dataset size:", len(y))
print("Resampled dataset size:", len(y_resampled))

Original dataset size: 5157
Resampled dataset size: 1282

In [27]:

from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)

X_resampled, y_resampled = ros.fit_resample(X, y)

In [28]:
print("Original dataset size:", len(y))
print("Resampled dataset size:", len(y_resampled))

Original dataset size: 5157
Resampled dataset size: 9032

In [29]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)

In [30]:
smote

SMOTE(random_state=42)

In [41]:
import numpy as np
import pandas as pd
df = pd.read_csv('Raisin_Dataset.csv')
df.head(5)

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040,Kecimen
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786,Kecimen
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,Kecimen
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,Kecimen
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251,Kecimen

In [42]:
df.shape

(900, 8)

In [43]:
df.isnull().sum()

Area               0
MajorAxisLength    0
MinorAxisLength    0
Eccentricity       0
ConvexArea         0
Extent             0
Perimeter          0
Class              0
dtype: int64

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df.Class.value_counts()

Class
Kecimen    450
Besni      450
Name: count, dtype: int64

In [46]:
df["Class"] = df["Class"].map({
    "Kecimen" : 1,
    "Besni" :0
})
df.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040,1
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786,1
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,1
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,1
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251,1

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [48]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators = 10,
    criterion = "gini",
    max_depth = 100,
    random_state = 42
)

In [49]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9728682170542635

In [52]:
model.score(X_test,y_test)

0.9728682170542635

In [53]:
model.score(X_train,y_train)

0.9980606060606061

In [56]:
from sklearn.metrics import classification_report
report = classification_report(
    y_test,
    y_pred,
)
print(report)

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       896
           1       0.97      0.82      0.89       136

    accuracy                           0.97      1032
   macro avg       0.97      0.91      0.94      1032
weighted avg       0.97      0.97      0.97      1032

In [59]:
import pickle
pickle.dump(model, open("rizz.pkl" , "wb"))